name: CleanShop
main: net.omnikraft.CleanShop.CleanShop
version: 1.0.1
description: Allows users to search shops for items they want.
author: PeculiarCarrot
depend: [WorldGuard]

commands:
   createshop:
      description: Creates a new shop in the region the user is standing in
      usage: /createShop [region]
      permission: cleanshop.createshop
      permission-message: You don't have permission!
   removeshop:
      description: Removes the given shop
      usage: /removeShop <region>
      permission: cleanshop.removeshop
      permission-message: You don't have permission!
   listshops:
      description: Lists all shops
      usage: /listShops
      permission-message: You don't have permission!
   searchShops:
      description: Returns a list of all shops with the given item
      usage: /searchShops <item>
      permission-message: You don't have permission!
   setShopTeleport:
      description: Sets the shop's teleport location. /sst works the same way.
      usage: /setShopTeleport [shop]
      aliases: [sst]
      permission: cleanshop.setshopteleport
      permission-message: You don't have permission!
   reloadShops:
      description: Reloads all shops from the file. /rls works the same way.
      usage: /reloadShops
      aliases: [rls]
      permission: cleanshop.reloadshops
      permission-message: You don't have permission!
   tpShop:
      description: Teleports to the given shop
      usage: /tpShop <shop>
      permission-message: You don't have permission!
   relocateShop:
      description: Relocates the given shop to the given region
      usage: /relocateShop <shop> [newRegion]
      permission: cleanshop.relocateshop
      permission-message: You don't have permission!